version: '3.8'
services:
  app:
    build: .
    container_name: weather_app
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  tests:
    build: .
    container_name: tests
    depends_on:
      - app
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    entrypoint: ["pytest", "-q"]

